---
title: "Expert advice from experts"
author:
- familyname: Curie
  othernames: Marie
  address: University of Paris
  qualifications: Nobel Prize, PhD
- familyname: Curie
  othernames: Pierre
  address: University of Paris
  qualifications: Nobel Prize, PhD
email: mcurie.notreal@gmail.com
phone: (03) 9905 2478
department: Department of\newline Econometrics &\newline Business Statistics
organization: Acme Corporation
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  monash::report:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE)
library(ggplot2)
library(tidyverse)
```

```{r data, message=FALSE}
covid<-read_csv(file=here::here("data/worldwidecases.csv"))
```

# Section 2

```{r a, fig.cap="Rates of covid cases over time"}
covidrate_vis <- covid %>% 
mutate(date=as.Date(dateRep,format="%d/%m/%y"), cases_rates=((1000*cases/popData2018)+0.01), dead_rates=((1000*deaths/popData2018)+0.01))%>% dplyr::filter(date != "2020-12-31") %>% 
  dplyr::filter(countriesAndTerritories %in% 
                  c("Italy", 
                    "Germany")) %>% 
  ggplot(aes(x = date,y = cases_rates) ) + 
  geom_line(color = "#1F9E8E") + facet_wrap(~countriesAndTerritories) + 
  theme_bw() + 
  ggtitle("Covidcases (rates)") 

covidrate_vis
```
In figure, \@ref(fig:a) we observe the COVID-19 rates for Italy and Germany.



